### ISSUE TITLE
[portal-deployment] Portal CCE 이슈

### ISSUE THREAD

**Issue by okpc579** [PaaS-TA/portal-deployment#6]
CCE 이슈 목록

|종류|Deployment명|호스트명|CCE-ID|점검항목|
|------|---|---|---|--|
|Linux|portal-ui|mariadb|U-16|world writable 파일 점검|
|Linux|portal-api|mariadb|U-16|world writable 파일 점검|
|Linux|portal-container-infra|portal-infra|U-16|world writable 파일 점검|
|Apache|portal-ui|paas-ta-portal-webuser|WA-02|불필요한 파일 제거|
|Apache|portal-ui|paas-ta-portal-webuser|WA-03|링크 사용금지|
|Apache|portal-ui|paas-ta-portal-webuser|WA-04|파일 업로드 및 다운로드 제한|
|MySQL|portal-ui|mariadb|DY-07|안전한 암호화 알고리즘 사용|
|MySQL|portal-api|mariadb|DY-07|안전한 암호화 알고리즘 사용|
|MySQL|portal-container-infra|portal-infra|DY-07|안전한 암호화 알고리즘 사용|
|MySQL|portal-ui|mariadb|DY-08|로그 활성화|
|MySQL|portal-api|mariadb|DY-08|로그 활성화|
|MySQL|portal-container-infra|portal-infra|DY-08|로그 활성화|
|MySQL|portal-ui|mariadb|DY-09|최신 패치 적용|
|MySQL|portal-api|mariadb|DY-09|최신 패치 적용|
|MySQL|portal-container-infra|portal-infra|DY-09|최신 패치 적용|

**Comment by jinhyojin** [comment]
[ [ world writable 파일 점검 ] https://github.com/PaaS-TA/paasta-deployment/pull/9](https://github.com/PaaS-TA/paasta-deployment/pull/9)

[ [ portal-api ] https://github.com/PaaS-TA/PAAS-TA-PORTAL-API-RELEASE/pull/4](https://github.com/PaaS-TA/PAAS-TA-PORTAL-API-RELEASE/pull/4)

[ [ portal-ui ] https://github.com/PaaS-TA/PAAS-TA-PORTAL-UI-RELEASE/pull/2](https://github.com/PaaS-TA/PAAS-TA-PORTAL-UI-RELEASE/pull/2)

[ [ portal-container-infra ] https://github.com/PaaS-TA/PAAS-TA-PORTAL-API-RELEASE/commit/34f5930ba0ddd3de17206921042baff033401857](https://github.com/PaaS-TA/PAAS-TA-PORTAL-API-RELEASE/commit/34f5930ba0ddd3de17206921042baff033401857)
